name: Nightly Codex Refactor

on:
  schedule:
    - cron: "0 3 * * *"    # daily at 03:00 UTC
  workflow_dispatch:

permissions:
  contents: write           # allow pushing branches
  pull-requests: write      # allow opening PRs

jobs:
  codex-refactor:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install "openai>=1.0.0"

      - name: Run Codex refactorer
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          OPENAI_MODEL: gpt-5-codex
          BASE_BRANCH: master
          CHANGE_BRANCH: codex/refactor-${{ github.run_id }}
        run: python .github/codex_refactor.py

      - name: Create PR
        uses: peter-evans/create-pull-request@v6
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ env.CHANGE_BRANCH }}
          title: "Nightly Codex Refactor"
          commit-message: "Nightly automated refactor (Codex)"
          body: |
            Automated refactor produced by Codex. Please review carefully.
          base: ${{ env.BASE_BRANCH }}
