name: Codex 01 – Refactor & DRY
on:
  schedule:
    - cron: "50 19 * * *"
  workflow_dispatch:

jobs:
  run:
    uses: ./.github/workflows/_codex-open-pr-and-ping.yml
    with:
      pr_title: "Codex: Implement refactor on latest master"
      pr_body: "Seed PR for Codex to implement the intended refactor atop current master."
      prompt: >
        Review the entire codebase with the goal of raising overall quality and maintainability. Identify duplicate, near-duplicate, or overly verbose code that can be consolidated, and refactor it to improve clarity and consistency. 
        Break down monolithic functions into smaller, more focused units and ensure the code is DRY, clean, and easy to understand. Avoid unnecessary abstraction—do not introduce classes or functions that add complexity without real 
        benefit—but re-implement outdated or incompatible code in a modern, clean way aligned with the current architecture. The objective is to deliver a streamlined, high-quality, and consistent codebase that is maintainable, 
        readable, and free of redundant logic.
      branch_prefix: "codex"
      base_branch: "master"