name: Codex 18 – Clarity Improvements
on:
  schedule:
    - cron: "39 */22 * * *" # every 22 hours
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write
  issues: write

jobs:
  run:
    uses: ./.github/workflows/_codex-open-pr-and-ping.yml
    secrets: inherit
    with:
      pr_title: "Codex: Clarity Improvements"
      pr_body: "Seed PR for Codex to improve readability and clarity atop current master."
      prompt: >
        Sweep the codebase and choose one coherent area (a module, small subsystem, or file cluster) where clarity can be materially improved without changing behavior. In that area, rename functions, variables, modules, or files to better reflect intent; add concise, high-signal inline comments only where context is missing (focus on why, not what); simplify control flow using early returns or guard clauses; extract helpers from large or duplicated blocks to improve readability and reuse, or inline trivial one-line wrappers that add no value; replace magic numbers with named constants; remove dead or redundant code paths; clarify units, ranges, and side effects; make parameter lists and return values self-describing by renaming, reordering, or grouping; standardize terminology across the touched files; and strengthen developer-facing surfaces with accurate JSDoc/docstrings for public functions. Keep the blast radius small, avoid API or behavior changes, add no new dependencies, make no style-only churn, and never delete tests. Update directly affected docs and comments to reflect the new names, and ensure npm run lint and npm test both pass.
