name: Codex 29 – Whimsical Enhancements

on:
  schedule:
    - cron: "5 6 */6 * *" # every 6 days at 06:05 UTC
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write
  issues: write

jobs:
  run:
    uses: ./.github/workflows/_codex-open-pr-and-ping.yml
    secrets: inherit
    with:
      pr_title: "Codex: Whimsical Enhancements"
      pr_body: "Seed PR for Codex to add an optional creative flourish that delights without breaking observability or performance."
      prompt: >
        Implement a tangible, user-facing 'whimsy' code change (no "no issues found" responses; find SOMETHING to make more whimsical in the codebase): ship a concrete enhancement on a coherent surface—event overlays, celebratory effects, UI copy, optional themes, playful logging, creative mode toggles, contextual tooltips, mood-based backgrounds—that adds delight without harming observability; ensure the feature is opt-in or unobtrusive by default, preserves performance (minimal per-frame allocations), maintains accessibility (contrast, motion sensitivity, ARIA labelling), updates documentation/tests and explains how to access the flourish in the PR body, and never removes existing functionality; only if you absolutely cannot ship code after a thorough audit, commit a `CHANGELOG.md` entry outlining at least three concrete whimsical ideas with implementation notes for future runs.
