name: Nightly Codex Refactor (CLI)

on:
  schedule:
    - cron: "50 19 * * *"   # daily at 19:50 UTC (3:50 PM in New York during DST)
  workflow_dispatch:

permissions:
  contents: write            # push branches / create commits
  pull-requests: write       # open PRs

jobs:
  codex-refactor:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Install Codex CLI
        run: npm install -g @openai/codex

      - name: Login Codex
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        run: codex login --api-key "$OPENAI_API_KEY"

      # --- Run Codex non-interactively on the repo itself ---
      - name: Run Codex refactor (full-auto)
        env:
          # Optional: make logs chattier if you’re debugging
          RUST_LOG: codex_core=info
        run: |
          codex exec --full-auto "
          Review the entire codebase with the goal of raising overall quality and maintainability.
          Identify duplicate or overly verbose code and refactor for clarity and consistency.
          Break down monolithic functions into smaller, focused units. Keep code DRY and readable.
          Avoid unnecessary abstraction; modernize outdated code to align with current architecture.
          Deliver a streamlined, high-quality, consistent codebase with no redundant logic.
          " || true

      # --- Open a PR with any changes that Codex made ---
      - name: Create PR
        uses: peter-evans/create-pull-request@v6
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          branch: codex/refactor-${{ github.run_id }}
          title: "Nightly Codex Refactor"
          commit-message: "Nightly automated refactor (Codex CLI)"
          body: |
            Automated refactor produced by Codex CLI (headless).
            Please review carefully before merging.
          base: master
