name: Codex 24 – Simplify

on:
  schedule:
    - cron: "0 0 * * SUN" # every 70 minutes rolling cadence
    - cron: "10 1 * * SUN"
    - cron: "20 2 * * SUN"
    - cron: "30 3 * * SUN"
    - cron: "40 4 * * SUN"
    - cron: "50 5 * * SUN"
    - cron: "0 7 * * SUN"
    - cron: "10 8 * * SUN"
    - cron: "20 9 * * SUN"
    - cron: "30 10 * * SUN"
    - cron: "40 11 * * SUN"
    - cron: "50 12 * * SUN"
    - cron: "0 14 * * SUN"
    - cron: "10 15 * * SUN"
    - cron: "20 16 * * SUN"
    - cron: "30 17 * * SUN"
    - cron: "40 18 * * SUN"
    - cron: "50 19 * * SUN"
    - cron: "0 21 * * SUN"
    - cron: "10 22 * * SUN"
    - cron: "20 23 * * SUN"
    - cron: "30 0 * * MON"
    - cron: "40 1 * * MON"
    - cron: "50 2 * * MON"
    - cron: "0 4 * * MON"
    - cron: "10 5 * * MON"
    - cron: "20 6 * * MON"
    - cron: "30 7 * * MON"
    - cron: "40 8 * * MON"
    - cron: "50 9 * * MON"
    - cron: "0 11 * * MON"
    - cron: "10 12 * * MON"
    - cron: "20 13 * * MON"
    - cron: "30 14 * * MON"
    - cron: "40 15 * * MON"
    - cron: "50 16 * * MON"
    - cron: "0 18 * * MON"
    - cron: "10 19 * * MON"
    - cron: "20 20 * * MON"
    - cron: "30 21 * * MON"
    - cron: "40 22 * * MON"
    - cron: "50 23 * * MON"
    - cron: "0 1 * * TUE"
    - cron: "10 2 * * TUE"
    - cron: "20 3 * * TUE"
    - cron: "30 4 * * TUE"
    - cron: "40 5 * * TUE"
    - cron: "50 6 * * TUE"
    - cron: "0 8 * * TUE"
    - cron: "10 9 * * TUE"
    - cron: "20 10 * * TUE"
    - cron: "30 11 * * TUE"
    - cron: "40 12 * * TUE"
    - cron: "50 13 * * TUE"
    - cron: "0 15 * * TUE"
    - cron: "10 16 * * TUE"
    - cron: "20 17 * * TUE"
    - cron: "30 18 * * TUE"
    - cron: "40 19 * * TUE"
    - cron: "50 20 * * TUE"
    - cron: "0 22 * * TUE"
    - cron: "10 23 * * TUE"
    - cron: "20 0 * * WED"
    - cron: "30 1 * * WED"
    - cron: "40 2 * * WED"
    - cron: "50 3 * * WED"
    - cron: "0 5 * * WED"
    - cron: "10 6 * * WED"
    - cron: "20 7 * * WED"
    - cron: "30 8 * * WED"
    - cron: "40 9 * * WED"
    - cron: "50 10 * * WED"
    - cron: "0 12 * * WED"
    - cron: "10 13 * * WED"
    - cron: "20 14 * * WED"
    - cron: "30 15 * * WED"
    - cron: "40 16 * * WED"
    - cron: "50 17 * * WED"
    - cron: "0 19 * * WED"
    - cron: "10 20 * * WED"
    - cron: "20 21 * * WED"
    - cron: "30 22 * * WED"
    - cron: "40 23 * * WED"
    - cron: "50 0 * * THU"
    - cron: "0 2 * * THU"
    - cron: "10 3 * * THU"
    - cron: "20 4 * * THU"
    - cron: "30 5 * * THU"
    - cron: "40 6 * * THU"
    - cron: "50 7 * * THU"
    - cron: "0 9 * * THU"
    - cron: "10 10 * * THU"
    - cron: "20 11 * * THU"
    - cron: "30 12 * * THU"
    - cron: "40 13 * * THU"
    - cron: "50 14 * * THU"
    - cron: "0 16 * * THU"
    - cron: "10 17 * * THU"
    - cron: "20 18 * * THU"
    - cron: "30 19 * * THU"
    - cron: "40 20 * * THU"
    - cron: "50 21 * * THU"
    - cron: "0 23 * * THU"
    - cron: "10 0 * * FRI"
    - cron: "20 1 * * FRI"
    - cron: "30 2 * * FRI"
    - cron: "40 3 * * FRI"
    - cron: "50 4 * * FRI"
    - cron: "0 6 * * FRI"
    - cron: "10 7 * * FRI"
    - cron: "20 8 * * FRI"
    - cron: "30 9 * * FRI"
    - cron: "40 10 * * FRI"
    - cron: "50 11 * * FRI"
    - cron: "0 13 * * FRI"
    - cron: "10 14 * * FRI"
    - cron: "20 15 * * FRI"
    - cron: "30 16 * * FRI"
    - cron: "40 17 * * FRI"
    - cron: "50 18 * * FRI"
    - cron: "0 20 * * FRI"
    - cron: "10 21 * * FRI"
    - cron: "20 22 * * FRI"
    - cron: "30 23 * * FRI"
    - cron: "40 0 * * SAT"
    - cron: "50 1 * * SAT"
    - cron: "0 3 * * SAT"
    - cron: "10 4 * * SAT"
    - cron: "20 5 * * SAT"
    - cron: "30 6 * * SAT"
    - cron: "40 7 * * SAT"
    - cron: "50 8 * * SAT"
    - cron: "0 10 * * SAT"
    - cron: "10 11 * * SAT"
    - cron: "20 12 * * SAT"
    - cron: "30 13 * * SAT"
    - cron: "40 14 * * SAT"
    - cron: "50 15 * * SAT"
    - cron: "0 17 * * SAT"
    - cron: "10 18 * * SAT"
    - cron: "20 19 * * SAT"
    - cron: "30 20 * * SAT"
    - cron: "40 21 * * SAT"
    - cron: "50 22 * * SAT"
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write
  issues: write

jobs:
  run:
    uses: ./.github/workflows/_codex-open-pr-and-ping.yml
    secrets: inherit
    with:
      pr_title: "Codex: Simplify Code Paths"
      pr_body: "Seed PR for Codex to streamline explicit logic while preserving existing behavior."
      prompt: |
        Identify one area of the codebase (a function, small module, or tight code path)
        that is overly explicit, verbose, or manually step-by-step, and condense it by
        using existing project utilities or language/framework built-ins—without
        changing behavior. This may include replacing hand-rolled loops, conditionals,
        parsing, cloning, formatting, state updates, or error checks with well-named
        helpers already in the codebase or idiomatic primitives (e.g., array/collection
        methods, standard library APIs); removing redundant local wrappers superseded by
        those helpers; unifying duplicate logic behind a single call site; or
        eliminating unnecessary intermediate variables. You must always produce at least
        one code change that simplifies or condenses something. Do not ever return with
        “no changes needed” or similar; if large opportunities are absent, make a small
        but concrete simplification instead (e.g., collapse two lines into one idiomatic
        call, inline an unnecessary temporary, or switch a manual loop to a single
        helper). Keep readability first: shorter code must be clearer, not clever. Limit
        scope to the chosen area, avoid architectural changes and new dependencies, and
        preserve public interfaces. In the commit message, include small before/after
        notes explaining what was simplified and why.
