name: Codex 01 – Refactor & DRY
on:
  schedule:
    - cron: "50 19 * * *"
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write
  issues: write

jobs:
  run:
    uses: ./.github/workflows/_codex-open-pr-and-ping.yml
    secrets: inherit
    with:
      pr_title: "Codex: Implement refactor on latest master"
      pr_body: "Seed PR for Codex to implement the intended refactor atop current master."
      prompt: >
        Review the entire codebase with the long-term goal of raising overall quality and 
        maintainability (DRY, clarity, consistency, modern APIs, minimal abstraction). 
        For this task, select one high-impact area (a module, file, or pattern) that will 
        materially improve readability or reduce duplication, and briefly justify your 
        choice. Then implement a minimal, focused refactor that improves clarity and 
        consistency while keeping behavior identical, avoiding unnecessary abstraction or 
        repo-wide churn. Ensure changes are self-contained, tested, and documented as 
        needed, with no reduction in test coverage and all CI checks passing.
      branch_prefix: "codex"
      base_branch: "master"