name: Codex 35 – Core Law Validation

on:
  schedule:
    - cron: "29 5,17 * * *" # twice daily at 05:29 and 17:29 UTC
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write
  issues: write

jobs:
  run:
    uses: ./.github/workflows/_codex-open-pr-and-ping.yml
    secrets: inherit
    with:
      pr_title: "Codex: Core Law Validation"
      pr_body: "Seed PR for Codex to audit core simulation laws and land one targeted improvement."
      prompt: >
        Create one targeted change to the codebase that strengthens alignment with the Simulation Laws defined in the README, which are essential to maintaining the integrity and realism of the simulation. Audit the existing code, documentation, and tests to identify the highest-priority gap, such as outdated or missing documentation, behavior drift, insufficient safeguards, or missing regression coverage. You must always be able to identify some improvement opportunity related to these laws. The change should be narrow in scope—for example, tightening logic, clarifying or expanding documentation, or adding or adjusting tests—and should avoid broad refactors. Commit the change with a clear explanation of the evidence you investigated, a direct reference to the relevant Simulation Law(s) as justification, and confirmation that the update preserves the project's performance and accessibility expectations.
