name: Codex 22 – Bug Fix
on:
  schedule:
    - cron: "40 11,23 * * *" # twice daily at 11:40, 23:40 UTC
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write
  issues: write

jobs:
  run:
    uses: ./.github/workflows/_codex-open-pr-and-ping.yml
    secrets: inherit
    with:
      pr_title: "Codex: Targeted Bug Fix"
      pr_body: "Seed PR for Codex to diagnose and fix a single bug atop current master."
      prompt: >
        Audit the codebase to identify one reproducible bug that impacts users, core
        functionality, or simulation flow. Confirm the issue with a clear and reliable
        reproduction, then implement the smallest safe fix that resolves it without
        introducing regressions or altering unrelated behavior. Strengthen coverage by
        adding or adjusting automated tests to lock in the fix. Keep the change set
        minimal, focused, and easy to review—deliver one end-to-end, reliable bug fix
        rather than broad rewrites.
