name: Codex 29 – Whimsical Enhancements

on:
  schedule:
    - cron: "5 6 * * *" # daily at 06:05 UTC
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write
  issues: write

jobs:
  run:
    uses: ./.github/workflows/_codex-open-pr-and-ping.yml
    secrets: inherit
    with:
      pr_title: "Codex: Whimsical Enhancements"
      pr_body: "Seed PR for Codex to add an optional creative flourish that delights without breaking observability or performance."
      prompt: >
        Create a code change to infuse the simulation with a tasteful dose of whimsy while respecting core
        functionality and observability. Choose a contained area (e.g. event overlays,
        birth/death celebrations, UI microcopy, optional visual themes) and ship a
        feels-good enhancement that helps players connect with the world. Ideas include:
        celebratory particle bursts after reproduction, colour palettes, dynamic
        background gradients tied to ecosystem health, playful tooltips or microcopy,
        an optional “creative mode” toggle that layers in extra personality, or a "violence" 
        mode that adds exaggerated effects for combat interactions.

        Requirements:
          • The addition must be opt-in or unobtrusive by default, with config/UI hooks so
            users can enable/disable it.
          • Preserve performance—avoid heavy per-frame allocations—and keep visuals
            accessible (contrast, motion considerations).
          • Update documentation and tests where behaviour changes; explain how to use the
            new flourish in the PR body.
          • Do not remove existing features or compromise observability—the goal is playful
            creativity that coexists with serious analysis tools.

        If you cannot find a delightful idea that meets these constraints, add a comment to the
        CHANGELOG.md noting the missed opportunity and suggesting future possibilities.
