name: Codex 27 – Observability
on:
  schedule:
    - cron: "17 3,15 * * *" # twice daily at 03:17, 15:17 UTC
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write
  issues: write

jobs:
  run:
    uses: ./.github/workflows/_codex-open-pr-and-ping.yml
    secrets: inherit
    with:
      pr_title: "Codex: Observability Enhancements"
      pr_body: "Seed PR for Codex to elevate visual observability across the ecosystem simulation."
      prompt: >
        Conduct a deep pass on simulation observability and land tangible improvements
        in this run. Pick a specific surface (overlay system, metrics dashboard, brain
        inspection tools, or event feedback) and ship a meaningful enhancement that
        materially increases a player's ability to see what organisms, genes, and events
        are doing. The pull request must include at least one code change that either:
        (a) adds a new visualisation (e.g. event log panel, birth/death markers, neuron
        activity display, mini timeline, sparkline graphs), (b) upgrades an existing
        tool with clearer signals (colour cues, legends, threshold indicators, dynamic
        summaries), or (c) introduces diagnostic hooks (structured event history, brain
        snapshots, filterable stats) that visualize or expose hidden state. If you truly cannot deliver
        a large feature, add a smaller win, for example adding a visual cue when
        mutation rate sliders change. 

        Do not respond with "found no major issues" or similar—produce SOMETHING. Be sure to update
        documentation/tests when behaviour changes as appropriate. Maintain architectural boundaries (simulation logic vs
        rendering vs UI), ensure additions are performant (no unnecessary per-frame
        allocations), keep visuals accessible, and avoid heavyweight dependencies. If a
        new configuration toggle is needed, add sensible defaults and document them.
