name: Codex 03 – Improve Performance
on:
  schedule:
    - cron: "15 * * * *" # hourly at 15 minutes past each hour UTC
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write
  issues: write

jobs:
  run:
    uses: ./.github/workflows/_codex-open-pr-and-ping.yml
    secrets: inherit
    with:
      pr_title: "Codex: Improve Performance"
      pr_body: "Seed PR for Codex to implement the intended performance-improvement atop current master."
      prompt: >
        Profile and analyze the codebase to identify performance bottlenecks. Select one
        high-impact area (such as a module, file, or method) that, if optimized, will
        materially improve speed or scalability. One valid targeted area is any
        operation currently running in O(n²); prioritize refactors that reduce its
        complexity or constrain its growth. Refactor that area by eliminating
        unnecessary computations, reducing memory overhead, or consolidating redundant
        database/API calls. Where appropriate, cache repeated work, simplify data
        structures, or replace heavy operations with lighter alternatives. Ensure the
        optimization preserves readability and maintainability, and validate the changes
        with profiling or benchmarks to confirm measurable gains without regressions.
