name: Codex 01 – Refactor & DRY
on:
  schedule:
    - cron: '0 0,12 * * *' # twice daily at 00:00, 12:00 UTC
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write
  issues: write

jobs:
  run:
    uses: ./.github/workflows/_codex-open-pr-and-ping.yml
    secrets: inherit
    with:
      pr_title: 'Codex: Implement refactor on latest master'
      pr_body: 'Seed PR for Codex to implement the intended refactor atop current master.'
      prompt: >
        The long-term goal is to raise the overall quality and 
        maintainability of the codebase (DRY, clarity, consistency, modern APIs, minimal abstraction). 
        Identify one high-impact area (a module, file, or pattern) that can be 
        materially improved to enhance readability or reduce duplication, and briefly justify your 
        choice. Then implement a minimal, focused refactor that improves clarity and 
        consistency while keeping behavior identical, avoiding unnecessary abstraction or 
        repo-wide churn.
