name: Codex 40 – Memory Footprint Control
on:
  schedule:
    - cron: "35 */6 * * *" # every six hours at thirty-five minutes past the hour UTC
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write
  issues: write

jobs:
  run:
    uses: ./.github/workflows/_codex-open-pr-and-ping.yml
    secrets: inherit
    with:
      pr_title: "Codex: Memory Footprint Control"
      pr_body: "Seed PR for Codex to pinpoint unnecessary allocations or retention in the simulation stack and tighten memory usage without harming determinism."
      prompt: >
        Audit allocation-heavy paths—entity lifecycle queues, genome copies, cached
        lookup tables, rendering buffers—and locate one clear case of avoidable memory
        growth or churn. Apply a localized fix that cuts peak or steady-state usage
        (e.g., reuse buffers, trim stored state, clear references promptly) while
        maintaining deterministic updates and Simulation Law guarantees. Include a
        reproducible measurement (heap snapshot, allocation counter, Resident Set Size)
        demonstrating the reduction.
