name: Codex 10 – Documentation Audit
on:
  schedule:
    - cron: "18 0 */3 * *" # every 3 days at 00:18 UTC
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write
  issues: write

jobs:
  run:
    uses: ./.github/workflows/_codex-open-pr-and-ping.yml
    secrets: inherit
    with:
      pr_title: "Codex: Documentation Audit"
      pr_body: "Seed PR for Codex to audit and improve documentation atop current master."
      branch_prefix: "codex"
      base_branch: "master"
      prompt: >
        Review and update all project documentation for accuracy, clarity, and completeness. Ensure README, architecture notes, changelogs, and developer guides reflect the current codebase, features, modules, and usage so contributors can onboard quickly and understand structure and conventions. Audit inline comments and docstrings so every public function, module, and complex piece of logic has concise, accurate explanations aligned with project style. Expand or add documentation where it is missing, remove outdated details, and keep edits practical and concise—avoiding speculative rewrites. The goal is a self-explanatory, accessible, and accurate codebase.
