name: Codex 24 – Simplify Code Paths

on:
  schedule:
    - cron: "45 8,20 * * *" # twice daily at 08:45, 20:45 UTC
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write
  issues: write

jobs:
  run:
    uses: ./.github/workflows/_codex-open-pr-and-ping.yml
    secrets: inherit
    with:
      pr_title: "Codex: Simplify Code Paths"
      pr_body: "Seed PR for Codex to streamline explicit logic while preserving existing behavior."
      prompt: |
        Identify one overly explicit, step-by-step area (a function, small module, or tight code path) and condense it by leveraging existing project utilities or language/framework built-ins—without changing behavior. Replace hand-rolled loops, conditionals, parsing, cloning, formatting, state updates, or error checks with well-named helpers already in the codebase or idiomatic primitives (e.g., array/collection methods, standard library APIs), remove redundant local wrappers superseded by those helpers, and unify duplicate logic behind a single call site. Keep readability first: shorter code must be clearer, not clever; add a brief comment only where intent isn't obvious. Limit scope to the chosen area, avoid architectural changes and new dependencies, and preserve public interfaces. Include small before/after notes in the commit message (what you simplified and why).
